# Generated by Django 6.0.4 on 2026-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_razon_social_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Refacciones', 'Refacciones'), ('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Llantas', 'Llantas'), ('Combustible', 'Combustible'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
