# Generated by Django 6.0.4 on 2026-05-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0001_initial'),
        ('vehiculos', '0012_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.IntegerField()),
                ('horario', models.CharField(choices=[('07:00 AM - 16:30 PM', '07:00 AM - 16:30 PM'), ('08:00 AM - 17:30 PM', '08:00 AM - 17:30 PM'), ('09:00 AM - 18:30 PM', '09:00 AM - 18:30 PM')], max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='operadores.operador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion')),
            ],
            options={
                'verbose_name': 'Asignación de Horario',
                'verbose_name_plural': 'Asignaciones de Horarios',
            },
        ),
    ]
