# Generated by Django 6.0.4 on 2026-05-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0002_asignacionhorario'),
        ('vehiculos', '0012_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionhorario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asignacionhorario',
            name='tienda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionhorario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion'),
        ),
    ]
