# Generated by Django 6.0.4 on 2026-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0003_alter_asignacionhorario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionhorario',
            name='tienda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
