# Generated by Django 6.0.4 on 2026-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0004_alter_asignacionhorario_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionhorario',
            name='es_personal',
            field=models.BooleanField(default=False),
        ),
    ]
