# Generated by Django 6.0.4 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0005_asignacionhorario_es_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionhorario',
            name='horario',
            field=models.CharField(choices=[('07:00 AM - 16:30 PM', '07:00 AM - 16:30 PM'), ('08:00 AM - 17:30 PM', '08:00 AM - 17:30 PM'), ('09:00 AM - 18:30 PM', '09:00 AM - 18:30 PM'), ('06:30 AM - 15:30 PM', '06:30 AM - 15:30 PM')], max_length=50),
        ),
    ]
