# Generated by Django 6.0.4 on 2026-05-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
        ('vehiculos', '0003_unidadtractocamion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.IntegerField(help_text='Número de tienda (10-390)')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='operadores.operador')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='vehiculos.unidadtractocamion')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
