# Generated by Django 6.0.4 on 2026-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estatus',
            field=models.CharField(choices=[('en_ruta', 'En Ruta'), ('en_tienda', 'En Tienda'), ('regresando', 'Regresando a CEDIS'), ('completado', 'Completado')], default='en_ruta', max_length=20),
        ),
    ]
