# Generated by Django 6.0.4 on 2026-05-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_viaje_estatus'),
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='ayudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_ayudante', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_operador', to='operadores.operador'),
        ),
    ]
