# Generated by Django 6.0.4 on 2026-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_viaje_ayudante_alter_viaje_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='bono_sancionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viaje',
            name='justificacion_sancion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
