# Generated by Django 6.0.4 on 2026-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_viaje_bono_sancionado_viaje_justificacion_sancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='tienda',
            field=models.IntegerField(blank=True, help_text='Número de tienda (10-390), dejar vacío para salida especial', null=True),
        ),
    ]
