# Generated by Django 6.0.4 on 2026-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_alter_viaje_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.DecimalField(decimal_places=1, max_digits=4, unique=True, verbose_name='Capacidad (Toneladas)')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Base de Bono')),
            ],
            options={
                'verbose_name': 'Configuración de Bono',
                'verbose_name_plural': 'Configuraciones de Bonos',
            },
        ),
    ]
