# Generated by Django 6.0.4 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_configuracionbono'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.CharField(blank=True, help_text='Destino específico para trailers o salidas especiales', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estatus',
            field=models.CharField(choices=[('en_ruta', 'En Ruta'), ('completado', 'Completado')], default='en_ruta', max_length=20),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
