# Generated by Django 6.0.4 on 2026-07-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_bitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='copias_descargadas',
            field=models.IntegerField(default=0, help_text='Número de copias descargadas de esta bitácora'),
        ),
    ]
