# Generated by Django 6.0.4 on 2026-05-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Factura')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio de Factura')),
                ('archivo_escaneado', models.FileField(upload_to='facturas/%Y/%m/', verbose_name='Documento Escaneado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='vehiculos.unidadtractocamion', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha'],
            },
        ),
    ]
