# Generated by Django 6.0.4 on 2026-05-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Producto/Servicio')),
                ('categoria', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Combustible', 'Combustible'), ('Operativo', 'Operativo'), ('Administrativo', 'Administrativo'), ('Refacciones', 'Refacciones'), ('Llantas', 'Llantas'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='facturacion.producto', verbose_name='Producto/Servicio'),
        ),
    ]
