# Generated by Django 6.0.4 on 2026-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_producto_factura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo_escaneado',
            field=models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/', verbose_name='Documento Escaneado'),
        ),
    ]
