# Generated by Django 6.0.4 on 2026-05-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_factura_archivo_escaneado'),
        ('vehiculos', '0008_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='vehiculos.unidadtractocamion', verbose_name='Unidad'),
        ),
    ]
