# Generated by Django 6.0.4 on 2026-05-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_factura_unidad'),
        ('vehiculos', '0012_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_interno', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Folio Interno')),
                ('folio_emision', models.CharField(max_length=50, verbose_name='Folio de Emisión')),
                ('fecha', models.DateField(verbose_name='Fecha del Ticket')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('archivo_escaneado', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/', verbose_name='Documento Escaneado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('convertido_en_factura', models.BooleanField(default=False, verbose_name='¿Facturado?')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='facturacion.producto', verbose_name='Producto/Servicio')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vehiculos.unidadtractocamion', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_vinculada', to='facturacion.ticket', verbose_name='Ticket Relacionado'),
        ),
    ]
