# Generated by Django 6.0.4 on 2026-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_ticket_factura_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='folio_emision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio de Emisión'),
        ),
    ]
