# Generated by Django 6.0.4 on 2026-05-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_ticket_folio_emision'),
        ('mantenimiento', '0009_alter_taller_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Breve'),
        ),
        migrations.AddField(
            model_name='factura',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_facturacion', to='mantenimiento.taller', verbose_name='Taller/Origen'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Breve'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_facturacion', to='mantenimiento.taller', verbose_name='Taller/Origen'),
        ),
    ]
