# Generated by Django 6.0.4 on 2026-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_descripcion_factura_taller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='razon_social_emisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social Emisor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='rfc_emisor',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC Emisor'),
        ),
    ]
