# Generated by Django 6.0.4 on 2026-05-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_factura_razon_social_emisor_factura_rfc_emisor'),
        ('proveedores', '0002_proveedor_razon_social_proveedor_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_facturacion', to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
