# Generated by Django 6.0.4 on 2026-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_factura_proveedor_ticket_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='categoria',
            field=models.CharField(choices=[('Mantenimiento y Refacciones', 'Mantenimiento y Refacciones'), ('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Llantas', 'Llantas'), ('Combustible', 'Combustible'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('Mantenimiento y Refacciones', 'Mantenimiento y Refacciones'), ('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Llantas', 'Llantas'), ('Combustible', 'Combustible'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría'),
        ),
    ]
