# Generated by Django 6.0.4 on 2026-05-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_factura_categoria_ticket_categoria'),
        ('vehiculos', '0013_unidadtractocamion_fecha_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='facturas_multiples', to='vehiculos.unidadtractocamion', verbose_name='Unidades Relacionadas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='tickets_multiples', to='vehiculos.unidadtractocamion', verbose_name='Unidades Relacionadas'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='vehiculos.unidadtractocamion', verbose_name='Unidad Principal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vehiculos.unidadtractocamion', verbose_name='Unidad Principal'),
        ),
    ]
