# Generated by Django 6.0.4 on 2026-05-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_factura_unidades_ticket_unidades_and_more'),
        ('vehiculos', '0013_unidadtractocamion_fecha_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalleUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_unidades', to='facturacion.factura')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion')),
            ],
            options={
                'verbose_name': 'Detalle de Gasto por Unidad (Factura)',
                'verbose_name_plural': 'Detalles de Gasto por Unidades (Facturas)',
                'unique_together': {('factura', 'unidad')},
            },
        ),
        migrations.CreateModel(
            name='TicketDetalleUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_unidades', to='facturacion.ticket')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion')),
            ],
            options={
                'verbose_name': 'Detalle de Gasto por Unidad (Ticket)',
                'verbose_name_plural': 'Detalles de Gasto por Unidades (Tickets)',
                'unique_together': {('ticket', 'unidad')},
            },
        ),
    ]
