# Generated by Django 6.0.4 on 2026-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_facturadetalleunidad_ticketdetalleunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='iva_aplicado',
            field=models.BooleanField(default=False, verbose_name='IVA Aplicado'),
        ),
    ]
