# Generated by Django 6.0.4 on 2026-05-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_factura_iva_aplicado'),
        ('vehiculos', '0014_remolquecaja_modelo_remolquecaja_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='vehiculos.remolquecaja', verbose_name='Caja/Remolque'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vehiculos.remolquecaja', verbose_name='Caja/Remolque'),
        ),
    ]
