# Generated by Django 6.0.4 on 2026-05-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_factura_caja_ticket_caja'),
        ('vehiculos', '0015_vehiculovariado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='variado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='vehiculos.vehiculovariado', verbose_name='Vehículo Variado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='variado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='vehiculos.vehiculovariado', verbose_name='Vehículo Variado'),
        ),
    ]
