# Generated by Django 6.0.4 on 2026-05-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_factura_variado_ticket_variado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='¿Cancelada?'),
        ),
        migrations.AddField(
            model_name='factura',
            name='factura_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_reemplazadas', to='facturacion.factura', verbose_name='Factura de Reemplazo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
