# Generated by Django 6.0.4 on 2026-05-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_factura_cancelado_factura_factura_reemplazo_and_more'),
        ('vehiculos', '0015_vehiculovariado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturadetalleunidad',
            unique_together={('factura', 'unidad')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketdetalleunidad',
            unique_together={('ticket', 'unidad')},
        ),
        migrations.AddField(
            model_name='factura',
            name='cajas',
            field=models.ManyToManyField(blank=True, related_name='facturas_multiples_cajas', to='vehiculos.remolquecaja', verbose_name='Cajas Relacionadas'),
        ),
        migrations.AddField(
            model_name='factura',
            name='variados',
            field=models.ManyToManyField(blank=True, related_name='facturas_multiples_variados', to='vehiculos.vehiculovariado', verbose_name='Vehículos Variados Relacionados'),
        ),
        migrations.AddField(
            model_name='facturadetalleunidad',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.remolquecaja'),
        ),
        migrations.AddField(
            model_name='facturadetalleunidad',
            name='variado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculovariado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cajas',
            field=models.ManyToManyField(blank=True, related_name='tickets_multiples_cajas', to='vehiculos.remolquecaja', verbose_name='Cajas Relacionadas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='variados',
            field=models.ManyToManyField(blank=True, related_name='tickets_multiples_variados', to='vehiculos.vehiculovariado', verbose_name='Vehículos Variados Relacionados'),
        ),
        migrations.AddField(
            model_name='ticketdetalleunidad',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.remolquecaja'),
        ),
        migrations.AddField(
            model_name='ticketdetalleunidad',
            name='variado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculovariado'),
        ),
        migrations.AlterField(
            model_name='facturadetalleunidad',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion'),
        ),
        migrations.AlterField(
            model_name='ticketdetalleunidad',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.unidadtractocamion'),
        ),
        migrations.AlterUniqueTogether(
            name='facturadetalleunidad',
            unique_together={('factura', 'caja'), ('factura', 'unidad'), ('factura', 'variado')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketdetalleunidad',
            unique_together={('ticket', 'caja'), ('ticket', 'unidad'), ('ticket', 'variado')},
        ),
    ]
