# Generated by Django 6.0.4 on 2026-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_alter_facturadetalleunidad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='categoria',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Refacciones', 'Refacciones'), ('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Llantas', 'Llantas'), ('Combustible', 'Combustible'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Refacciones', 'Refacciones'), ('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Llantas', 'Llantas'), ('Combustible', 'Combustible'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Categoría'),
        ),
    ]
