# Generated by Django 6.0.4 on 2026-06-22 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_alter_factura_categoria_alter_ticket_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo del Cambio')),
                ('cambios_propuestos', models.JSONField(verbose_name='Cambios Propuestos')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cambio_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizador')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='facturacion.factura', verbose_name='Factura a Modificar')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Capturista)')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Factura',
                'verbose_name_plural': 'Solicitudes de Cambio de Facturas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
