# Generated by Django 6.0.4 on 2026-07-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_solicitudcambiofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambiofactura',
            name='nuevo_archivo_escaneado',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes_facturas/%Y/%m/', verbose_name='Nuevo Documento Escaneado'),
        ),
    ]
