# Generated by Django 6.0.4 on 2026-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_solicitudcambiofactura_nuevo_archivo_escaneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='resico_aplicado',
            field=models.BooleanField(default=False, verbose_name='RESICO Aplicado'),
        ),
    ]
