# Generated by Django 6.0.4 on 2026-07-20 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_factura_resico_aplicado'),
        ('mantenimiento', '0012_alter_taller_direccion'),
        ('proveedores', '0003_alter_proveedor_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio Contra Recibo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('resico_aplicado', models.BooleanField(default=False, verbose_name='RESICO Aplicado')),
                ('total_facturas', models.IntegerField(default=0, verbose_name='Total de Facturas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('capturista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Capturista')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contra_recibos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contra_recibos', to='mantenimiento.taller', verbose_name='Taller/Origen')),
            ],
            options={
                'verbose_name': 'Contra Recibo',
                'verbose_name_plural': 'Contra Recibos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContraReciboFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_factura', models.CharField(max_length=100, verbose_name='Folio Factura')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('estado', models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Aceptada', max_length=20, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación para el proveedor')),
                ('contra_recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_detalle', to='facturacion.contrarecibo')),
            ],
            options={
                'verbose_name': 'Factura de Contra Recibo',
                'verbose_name_plural': 'Facturas de Contra Recibos',
            },
        ),
    ]
