# Generated by Django 6.0.4 on 2026-05-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0004_unidadtractocamion_fecha_ultima_carga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('precio_magna', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Magna')),
                ('precio_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Premium')),
                ('precio_diesel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Diesel')),
            ],
            options={
                'verbose_name': 'Precio de Combustible',
                'verbose_name_plural': 'Precios de Combustible',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Carga')),
                ('tipo_combustible', models.CharField(choices=[('magna', 'Magna'), ('premium', 'Premium'), ('diesel', 'Diesel')], max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Litro')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros Cargados')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kilometraje')),
                ('ignorar_kilometraje', models.BooleanField(default=False, verbose_name='Ignorar Kilometraje')),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendimiento (km/l)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='vehiculos.unidadtractocamion')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
