# Generated by Django 6.0.4 on 2026-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargacombustible',
            name='kilometraje',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
    ]
