# Generated by Django 6.0.4 on 2026-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0002_alter_cargacombustible_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciocombustible',
            name='precio_electrico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Eléctrico'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='tipo_combustible',
            field=models.CharField(choices=[('magna', 'Magna'), ('premium', 'Premium'), ('diesel', 'Diesel'), ('electrico', 'Eléctrico')], max_length=20),
        ),
    ]
