# Generated by Django 6.0.4 on 2026-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0003_preciocombustible_precio_electrico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='es_especial',
            field=models.BooleanField(default=False, verbose_name='¿Es Carga Especial?'),
        ),
    ]
