# Generated by Django 6.0.4 on 2026-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0004_cargacombustible_es_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='km_equivocado',
            field=models.BooleanField(default=False, verbose_name='¿Kilometraje Equivocado?'),
        ),
    ]
