# Generated by Django 6.0.4 on 2026-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0005_cargacombustible_km_equivocado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciocombustible',
            name='precio_gas_lp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Gas LP'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='tipo_combustible',
            field=models.CharField(choices=[('magna', 'Magna'), ('premium', 'Premium'), ('diesel', 'Diesel'), ('electrico', 'Eléctrico'), ('gas_lp', 'Gas LP')], max_length=20),
        ),
    ]
