# Generated by Django 6.0.4 on 2026-06-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0006_preciocombustible_precio_gas_lp_and_more'),
        ('vehiculos', '0016_alter_unidadtractocamion_tipo_combustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='unidad_variada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='vehiculos.vehiculovariado'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='vehiculos.unidadtractocamion'),
        ),
    ]
