# Generated by Django 6.0.4 on 2026-06-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0007_cargacombustible_unidad_variada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueCargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Registro')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('total_litros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Bloque de Carga',
                'verbose_name_plural': 'Bloques de Cargas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='bloque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='combustibles.bloquecargacombustible'),
        ),
    ]
