# Generated by Django 4.2 on 2026-06-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0014_fix_special_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquecargacombustible',
            name='total_litros',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='litros',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Litros Cargados'),
        ),
    ]
