# Generated by Django 6.0.4 on 2026-07-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0015_alter_cargacombustible_litros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_factura', models.CharField(max_length=100, verbose_name='Folio de Factura')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo_escaneado', models.FileField(blank=True, null=True, upload_to='evidencia_gas/%Y/%m/', verbose_name='Documento Escaneado')),
                ('fecha', models.DateField(verbose_name='Fecha de Carga')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evidencia de Gas',
                'verbose_name_plural': 'Evidencias de Gas',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
