# Generated by Django 6.0.4 on 2026-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustibles', '0016_evidenciagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciagas',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
    ]
