# Generated by Django 6.0.4 on 2026-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='archivo_escaneado',
            field=models.FileField(blank=True, null=True, upload_to='mantenimiento/facturas/'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
