# Generated by Django 6.0.4 on 2026-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('mantenimiento', '0002_ordentrabajo_archivo_escaneado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='facturas',
            field=models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='facturacion.factura'),
        ),
    ]
