# Generated by Django 6.0.4 on 2026-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_ordentrabajo_facturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='correctivo', max_length=20),
        ),
    ]
