# Generated by Django 6.0.4 on 2026-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_ordentrabajo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en proceso', 'En Proceso'), ('en espera', 'En Espera'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
