# Generated by Django 6.0.4 on 2026-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_alter_ordentrabajo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_espera',
            field=models.CharField(blank=True, choices=[('falta_refaccion', 'Falta de pieza/refacción'), ('taller_lleno', 'Sin espacio en taller'), ('falta_presupuesto', 'Aprobación de presupuesto'), ('otro', 'Otro motivo')], max_length=50, null=True),
        ),
    ]
