# Generated by Django 6.0.4 on 2026-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_taller_ordentrabajo_taller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estatus',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('en espera', 'En Espera'), ('completado', 'Completado')], default='en proceso', max_length=20),
        ),
        migrations.AlterField(
            model_name='taller',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Motores Diesel', 'Motores Diesel'), ('Frenos y Suspensión', 'Frenos y Suspensión'), ('Transmisiones', 'Transmisiones'), ('Eléctrico', 'Eléctrico / Electrónico'), ('Llantas', 'Llantas'), ('Carrocería', 'Carrocería y Pintura'), ('Mantenimiento General', 'Mantenimiento General'), ('Hidráulico', 'Hidráulico')], max_length=100, null=True),
        ),
    ]
