# Generated by Django 6.0.4 on 2026-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_ordentrabajo_estatus_alter_taller_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
