# Generated by Django 6.0.4 on 2026-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_descripcion_factura_taller_and_more'),
        ('mantenimiento', '0009_alter_taller_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='facturacion.ticket'),
        ),
    ]
