# Generated by Django 6.0.4 on 2026-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_ordentrabajo_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social / Nombre Emisor'),
        ),
        migrations.AddField(
            model_name='taller',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
