# Generated by Django 6.0.4 on 2026-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_taller_razon_social_taller_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
