# Generated by Django 6.0.4 on 2026-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('capturista', 'Capturista'), ('jefe_logistica', 'Jefe de Logística')], default='capturista', max_length=20),
        ),
    ]
