# Generated by Django 6.0.4 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin_general', 'Administrador General'), ('admin', 'Administrador'), ('capturista', 'Capturista'), ('jefe_logistica', 'Jefe de Logística'), ('monitoreo', 'Monitoreo')], default='capturista', max_length=20),
        ),
    ]
