# Generated by Django 6.0.4 on 2026-06-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles de la Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
