# Generated by Django 6.0.4 on 2026-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_historialaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin_general', 'Administrador General'), ('admin', 'Administrador'), ('capturista', 'Capturista'), ('jefe_logistica', 'Jefe de Logística'), ('monitoreo', 'Monitoreo'), ('lector_gastos', 'Lector de Gastos')], default='capturista', max_length=20),
        ),
    ]
