# Generated by Django 6.0.4 on 2026-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractocamion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/unidades/'),
        ),
        migrations.AddField(
            model_name='unidadtractocamion',
            name='numero_vin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
