# Generated by Django 6.0.4 on 2026-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_unidadtractocamion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractocamion',
            name='estado',
            field=models.CharField(choices=[('operativa', 'Operativa'), ('en_mantenimiento', 'En Mantenimiento')], default='operativa', max_length=20),
        ),
    ]
