# Generated by Django 6.0.4 on 2026-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_unidadtractocamion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractocamion',
            name='fecha_ultima_carga',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Última Carga'),
        ),
        migrations.AddField(
            model_name='unidadtractocamion',
            name='ignorar_kilometraje',
            field=models.BooleanField(default=False, verbose_name='Ignorar Kilometraje (Odómetro dañado)'),
        ),
        migrations.AddField(
            model_name='unidadtractocamion',
            name='ultimo_kilometraje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Último Kilometraje'),
        ),
        migrations.AddField(
            model_name='unidadtractocamion',
            name='ultimo_rendimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Último Rendimiento (km/l)'),
        ),
    ]
