# Generated by Django 6.0.4 on 2026-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtractocamion',
            name='capacidad',
            field=models.DecimalField(choices=[('1.5', '1.5 Toneladas'), ('3.5', '3.5 Toneladas'), ('10.0', '10 Toneladas')], decimal_places=1, default='10.0', max_digits=4, verbose_name='Capacidad (Toneladas)'),
        ),
    ]
