# Generated by Django 6.0.4 on 2026-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractocamion',
            name='tipo_combustible',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('magna', 'Gasolina Magna'), ('premium', 'Gasolina Premium'), ('electrico', 'Eléctrico')], default='diesel', max_length=20, verbose_name='Tipo de Combustible'),
        ),
    ]
