# Generated by Django 6.0.4 on 2026-05-07 19:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0010_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtractocamion',
            name='capacidad',
            field=models.DecimalField(choices=[(Decimal('0.0'), 'Vehículo Ligero (Auto/Camioneta)'), (Decimal('1.5'), '1.5 Toneladas'), (Decimal('3.5'), '3.5 Toneladas'), (Decimal('10.0'), '10 Toneladas'), (Decimal('30.0'), 'Trailer / Full')], decimal_places=1, default=Decimal('10.0'), max_digits=4, verbose_name='Capacidad (Toneladas)'),
        ),
    ]
