# Generated by Django 6.0.4 on 2026-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_alter_unidadtractocamion_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadtractocamion',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Mantenimiento'),
        ),
        migrations.AddField(
            model_name='unidadtractocamion',
            name='ultimo_kilometraje_mantenimiento',
            field=models.IntegerField(default=0, verbose_name='Km en Último Mantenimiento'),
        ),
    ]
