# Generated by Django 6.0.4 on 2026-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0013_unidadtractocamion_fecha_ultimo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remolquecaja',
            name='modelo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remolquecaja',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
