# Generated by Django 6.0.4 on 2026-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0014_remolquecaja_modelo_remolquecaja_numero_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoVariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_economico', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
