# Generated by Django 6.0.4 on 2026-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0015_vehiculovariado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadtractocamion',
            name='tipo_combustible',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('magna', 'Gasolina Magna'), ('premium', 'Gasolina Premium'), ('electrico', 'Eléctrico'), ('gas_lp', 'Gas LP')], default='diesel', max_length=20, verbose_name='Tipo de Combustible'),
        ),
    ]
