# Generated by Django 6.0.4 on 2026-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0016_alter_unidadtractocamion_tipo_combustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculovariado',
            name='fecha_ultima_carga',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Última Carga'),
        ),
        migrations.AddField(
            model_name='vehiculovariado',
            name='ultimo_kilometraje',
            field=models.IntegerField(default=0, verbose_name='Último Kilometraje/Horómetro'),
        ),
        migrations.AddField(
            model_name='vehiculovariado',
            name='ultimo_rendimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Último Rendimiento'),
        ),
    ]
